services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: "${DATABASE_URL}"
      VITE_WEATHERAPI_KEY: "${VITE_WEATHERAPI_KEY}"
    ports:
      - "3001:3000"
    restart: always
