/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeatherRouteRouteImport } from './routes/weather/route'
import { Route as TodologgedRouteRouteImport } from './routes/todologged/route'
import { Route as TodoRouteRouteImport } from './routes/todo/route'
import { Route as OthersRouteRouteImport } from './routes/others/route'
import { Route as LoginRouteRouteImport } from './routes/login/route'
import { Route as CalendarRouteRouteImport } from './routes/calendar/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as OthersSpalickyRouteRouteImport } from './routes/others/spalicky/route'
import { Route as OthersPokemonsRouteRouteImport } from './routes/others/pokemons/route'
import { Route as OthersGradesRouteRouteImport } from './routes/others/grades/route'
import { Route as DemoStartServerFuncsRouteImport } from './routes/demo/start.server-funcs'

const WeatherRouteRoute = WeatherRouteRouteImport.update({
  id: '/weather',
  path: '/weather',
  getParentRoute: () => rootRouteImport,
} as any)
const TodologgedRouteRoute = TodologgedRouteRouteImport.update({
  id: '/todologged',
  path: '/todologged',
  getParentRoute: () => rootRouteImport,
} as any)
const TodoRouteRoute = TodoRouteRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const OthersRouteRoute = OthersRouteRouteImport.update({
  id: '/others',
  path: '/others',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRouteRoute = LoginRouteRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarRouteRoute = CalendarRouteRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const OthersSpalickyRouteRoute = OthersSpalickyRouteRouteImport.update({
  id: '/spalicky',
  path: '/spalicky',
  getParentRoute: () => OthersRouteRoute,
} as any)
const OthersPokemonsRouteRoute = OthersPokemonsRouteRouteImport.update({
  id: '/pokemons',
  path: '/pokemons',
  getParentRoute: () => OthersRouteRoute,
} as any)
const OthersGradesRouteRoute = OthersGradesRouteRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => OthersRouteRoute,
} as any)
const DemoStartServerFuncsRoute = DemoStartServerFuncsRouteImport.update({
  id: '/demo/start/server-funcs',
  path: '/demo/start/server-funcs',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteRoute
  '/login': typeof LoginRouteRoute
  '/others': typeof OthersRouteRouteWithChildren
  '/todo': typeof TodoRouteRoute
  '/todologged': typeof TodologgedRouteRoute
  '/weather': typeof WeatherRouteRoute
  '/others/grades': typeof OthersGradesRouteRoute
  '/others/pokemons': typeof OthersPokemonsRouteRoute
  '/others/spalicky': typeof OthersSpalickyRouteRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteRoute
  '/login': typeof LoginRouteRoute
  '/others': typeof OthersRouteRouteWithChildren
  '/todo': typeof TodoRouteRoute
  '/todologged': typeof TodologgedRouteRoute
  '/weather': typeof WeatherRouteRoute
  '/others/grades': typeof OthersGradesRouteRoute
  '/others/pokemons': typeof OthersPokemonsRouteRoute
  '/others/spalicky': typeof OthersSpalickyRouteRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendar': typeof CalendarRouteRoute
  '/login': typeof LoginRouteRoute
  '/others': typeof OthersRouteRouteWithChildren
  '/todo': typeof TodoRouteRoute
  '/todologged': typeof TodologgedRouteRoute
  '/weather': typeof WeatherRouteRoute
  '/others/grades': typeof OthersGradesRouteRoute
  '/others/pokemons': typeof OthersPokemonsRouteRoute
  '/others/spalicky': typeof OthersSpalickyRouteRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/start/server-funcs': typeof DemoStartServerFuncsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendar'
    | '/login'
    | '/others'
    | '/todo'
    | '/todologged'
    | '/weather'
    | '/others/grades'
    | '/others/pokemons'
    | '/others/spalicky'
    | '/demo/tanstack-query'
    | '/demo/start/server-funcs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendar'
    | '/login'
    | '/others'
    | '/todo'
    | '/todologged'
    | '/weather'
    | '/others/grades'
    | '/others/pokemons'
    | '/others/spalicky'
    | '/demo/tanstack-query'
    | '/demo/start/server-funcs'
  id:
    | '__root__'
    | '/'
    | '/calendar'
    | '/login'
    | '/others'
    | '/todo'
    | '/todologged'
    | '/weather'
    | '/others/grades'
    | '/others/pokemons'
    | '/others/spalicky'
    | '/demo/tanstack-query'
    | '/demo/start/server-funcs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarRouteRoute: typeof CalendarRouteRoute
  LoginRouteRoute: typeof LoginRouteRoute
  OthersRouteRoute: typeof OthersRouteRouteWithChildren
  TodoRouteRoute: typeof TodoRouteRoute
  TodologgedRouteRoute: typeof TodologgedRouteRoute
  WeatherRouteRoute: typeof WeatherRouteRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoStartServerFuncsRoute: typeof DemoStartServerFuncsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weather': {
      id: '/weather'
      path: '/weather'
      fullPath: '/weather'
      preLoaderRoute: typeof WeatherRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todologged': {
      id: '/todologged'
      path: '/todologged'
      fullPath: '/todologged'
      preLoaderRoute: typeof TodologgedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/others': {
      id: '/others'
      path: '/others'
      fullPath: '/others'
      preLoaderRoute: typeof OthersRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendar': {
      id: '/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof CalendarRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/others/spalicky': {
      id: '/others/spalicky'
      path: '/spalicky'
      fullPath: '/others/spalicky'
      preLoaderRoute: typeof OthersSpalickyRouteRouteImport
      parentRoute: typeof OthersRouteRoute
    }
    '/others/pokemons': {
      id: '/others/pokemons'
      path: '/pokemons'
      fullPath: '/others/pokemons'
      preLoaderRoute: typeof OthersPokemonsRouteRouteImport
      parentRoute: typeof OthersRouteRoute
    }
    '/others/grades': {
      id: '/others/grades'
      path: '/grades'
      fullPath: '/others/grades'
      preLoaderRoute: typeof OthersGradesRouteRouteImport
      parentRoute: typeof OthersRouteRoute
    }
    '/demo/start/server-funcs': {
      id: '/demo/start/server-funcs'
      path: '/demo/start/server-funcs'
      fullPath: '/demo/start/server-funcs'
      preLoaderRoute: typeof DemoStartServerFuncsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OthersRouteRouteChildren {
  OthersGradesRouteRoute: typeof OthersGradesRouteRoute
  OthersPokemonsRouteRoute: typeof OthersPokemonsRouteRoute
  OthersSpalickyRouteRoute: typeof OthersSpalickyRouteRoute
}

const OthersRouteRouteChildren: OthersRouteRouteChildren = {
  OthersGradesRouteRoute: OthersGradesRouteRoute,
  OthersPokemonsRouteRoute: OthersPokemonsRouteRoute,
  OthersSpalickyRouteRoute: OthersSpalickyRouteRoute,
}

const OthersRouteRouteWithChildren = OthersRouteRoute._addFileChildren(
  OthersRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarRouteRoute: CalendarRouteRoute,
  LoginRouteRoute: LoginRouteRoute,
  OthersRouteRoute: OthersRouteRouteWithChildren,
  TodoRouteRoute: TodoRouteRoute,
  TodologgedRouteRoute: TodologgedRouteRoute,
  WeatherRouteRoute: WeatherRouteRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoStartServerFuncsRoute: DemoStartServerFuncsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
